### ISSUE TITLE
FR: support `.` after f in flash

### ISSUE THREAD

**Issue by RmZeta2718** [cuixiaorui/VSCodeVim#10]
**Is your feature request related to a problem? Please describe.**
目前 `.` 操作会记录 flash 的 `f`，因此 `f` 后无法使用 `.` 。这与 `/` 搜索和原生的 `f` 行为都不一致（ `/` 搜索之后可以 `n.n.` ，而当前的flash下无法 `f<flash op>.f<flash op>.`）。

**Describe the solution you'd like**
flash `f` 不覆盖 `.` 的操作记录。

**Comment by cuixiaorui** [comment]
下个版本修复

**Comment by cuixiaorui** [comment]
已经在  1.26.7 中修复哈
