### ISSUE TITLE
Port the `nvim-spider` to `VSCodeVim`

### ISSUE THREAD

**Issue by alexzhang1030** [cuixiaorui/VSCodeVim#5]
Port [`nvim-spider`](https://github.com/chrisgrieser/nvim-spider) to get a better move behaviour.

**Comment by cuixiaorui** [comment]
vscodeVim 中有一个类似的功能：

https://github.com/cuixiaorui/VSCodeVim#camelcasemotion

**Comment by alexnest** [comment]
Up until today, I've been using your 'leap' plugin without any issues. However, without making any changes to the settings, when I press the 's' key now, it no longer produces the expected 'leap' effect. Instead, it has turned into deleting the current character and change insert mode. I've tried reinstalling the pre-packaged 'vim-1.25.2.vsix,' but it doesn't seem to work either.

**Comment by cuixiaorui** [comment]
@alexnest 
The use of leap is no longer supported
Now using [flash](https://github.com/VSCodeVim/Vim/issues/8567)
If you have any problems, you can open a new issue This one is closed.
