### ISSUE TITLE
Implementing flash functionality in neovim

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/VSCodeVim#6]
https:github.com/folke/flash.nvim

because Falsh's mobile solution is more comfortable than leap

I'll make it happen while I'm on the live broadcast

**Comment by xiaojia21190** [comment]
flash 在本地反应很慢, 大概每个操作等待2s左右

**Comment by cuixiaorui** [comment]
close the issue 
When the time comes to synchronize to [the issue](https://github.com/VSCodeVim/Vim/issues/8567)
