### ISSUE TITLE
编辑器的「不生效/未激活」的配置项，半透明让flash.marker.backgroundColor识别起来很困难

### ISSUE THREAD

**Issue by hankjs** [cuixiaorui/VSCodeVim#7]
**Describe the bug**
编辑器的「不生效/未激活」的配置项，半透明让flash.marker.backgroundColor识别起来很困难

**To Reproduce**

1.  打开settings.json
2.  在不生效的插件配置上使用flash功能
3.  高亮后会叠加「不生效」的半透明样式，让flash的marker难以识别

**Expected behavior**
如题，详情请看截图

**Screenshots**
![image](https://github.com/cuixiaorui/VSCodeVim/assets/34299026/de4e38ac-4293-4a8c-a8ef-c14771bb5a31)

**Environment (please complete the following information):**

- Extension (CVim) version: 1.26.3
- VSCode version: 1.79.0
- OS: Windows

**Comment by cuixiaorui** [comment]
这个需要依赖 vscode 的 api 做支持
很久之前提过 [issue](https://github.com/microsoft/vscode/issues/170607)  不过至今没得到回复 [皱眉]
